id: A713B47F8
title: Short Maṇḍala Offering
type: translation
pechas:
- I83ADCA0A
- I63ACBB3C
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 11:31:24.961622
  last_modified_at: 2023-01-04 11:31:24.961635
  collections:
  - Chögyal Pakpa Lodrö Gyaltsen
  - Works of Tibetan Masters
alignment_to_base:
  I83ADCA0A/2684: E3A6
  I63ACBB3C/33ED: E3A6
